name: Feature request SK
description: Nový nápad alebo funkcia pre túto stránku
labels: [Feature request]
body:

  - type: textarea
    id: feature-description
    attributes:
      label: Popíšte vami navrhovanú funkciu
      description: Ako môže byť táto webová stránka vylepšená?
      placeholder: |
        Napríklad:
          "V nastaveniach by mala byť možnosť..."
    validations:
      required: true

  - type: textarea
    id: other-details
    attributes:
      label: Ďalšie informácie a/alebo snímky obrazovky
      placeholder: |
        Ďalšie podrobnosti a prílohy.

  - type: checkboxes
    id: acknowledgements
    attributes:
      label: Potvrdenia
      description: Prečítajte si toto poriadne, ak zistíme, že ste nevyplnili, to čo máte, vašu požiadavku uzavrieme a budeme ju ignorovať.
      options:
        - label: Vyhľadal som existujúce problémy v slovenčine a v angličtine a toto je **NOVÝ** problém, **NIE** duplikát, ani sa netýka iného otvoreného alebo uzavretého problému.
          required: true
        - label: Napísal som krátky, ale informatívny názov.
          required: true
        - label: Vyplním všetky požadované informácie v tomto formulári.
          required: true